version: '3.7'
services:
  backend:
    image: abetavarez/admin-backend
    environment:
      DB_HOST: db
      DB_DATABASE: admin
      DN_USERNAME: root
      DB_PASSWORD: root
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
